### ISSUE TITLE
Redesign follow up tracking issue 

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/site#148]
Following https://github.com/mimblewimble/site/pull/147, this issue keeps track of feedback and diffs that arose out of the merge. Even if they ultimately will not be actioned, it would be good to get each of these point _addressed_ and tagged as `will fix` / `won't fix`.

* [ ] Make Wiki/FAQ more prominent
* [ ] Collate "Friends of Grin" and "general fund" into a "Funding" area/section/category
* [ ] Iterate on descriptive wall of text on main page
   * Iterate on font and spacing of header?
   * Reduce copy of sub-headers into 1-2 words?
   * Add new icons?
* [ ] Replace any `grin-tech.org` URLs with the new `grin.mw` domain
* [ ] Links to SECURITY.md and repo
* [ ] Re-introduce missing content
   * Releases
   * Guides
   * Improve the website

community link now just links to community projects, but I think it should be a drop down including not only projects but the forum, the gitter, etc as the current site does.

**Comment by lehnberg** [comment]
Just merged https://github.com/mimblewimble/site/pull/149 which is related.

**Comment by Paouky** [comment]
> Iterate on font and spacing of header?
> Reduce copy of sub-headers into 1-2 words?
In my original comment I wrote headers but what I meant was headings, just clarifying.
I'll give it a go once I've got some time to spare.
